--borrado de constraints
ALTER TABLE [dbo].[BITACORA_CARGA_CALIFICACIONES] DROP CONSTRAINT [DF_BITACORA_CARGA_CALIFICACIONES_FECHA_REGISTRO];
ALTER TABLE [dbo].[BITACORA_GENERACION_REPORTE] DROP CONSTRAINT [DF_BITACORA_GENERACION_REPORTE_FECHA_REGISTRO];
ALTER TABLE [dbo].[BITACORA_MATERIAS_EXCEPCION] DROP CONSTRAINT [DF_BITACORA_MATERIAS_EXCEPCION_FECHA_REGISTRO];
ALTER TABLE [dbo].[BITACORA_MATERIAS_NORMATIVA] DROP CONSTRAINT [DF_BITACORA_MATERIAS_NORMATIVA_FECHA_REGISTRO];
ALTER TABLE [dbo].[BITACORA_NORMATIVA] DROP CONSTRAINT [DF_BITACORA_NORMATIVA_FECHA_REGISTRO];
ALTER TABLE [dbo].[BITACORA_PROCESO_AUTOMATICO] DROP CONSTRAINT [DF_BITACORA_PROCESO_AUTOMATICO];
ALTER TABLE [dbo].[BITACORA_ROLES_ADMIN] DROP CONSTRAINT [DF_BITACORA_ROLES_ADMIN_FECHA_REGISTRO];
ALTER TABLE [dbo].[BITACORA_SUBPERIODO_CAMPUS] DROP CONSTRAINT [DF_BITACORA_SUBPERIODO_CAMPUS_FECHA_REGISTRO];
ALTER TABLE [dbo].[BITACORA_SUBPERIODO_NACIONAL] DROP CONSTRAINT [DF_BITACORA_SUBPERIODO_NACIONAL_FECHA_REGISTRO];
ALTER TABLE [dbo].[CALIFICACIONES_ENVIADAS_BANNER] DROP CONSTRAINT [DF_CALIFICACIONES_ENVIADAS_BANNER_FECHA_AGREGADO];
--ALTER TABLE [dbo].[SUBPERIODOS_CAMPUS] DROP CONSTRAINT [DF_SUBPERIODOS_CAMPUS_NIVEL];
ALTER TABLE [dbo].[SUBPERIODOS_CAMPUS] DROP CONSTRAINT [DF_SUBPERIODOS_CAMPUS_FECHA_AGREGADO];
GO
--Borrado de las tablas
DROP TABLE [dbo].[ARCHIVO_CANVAS];
DROP TABLE [dbo].[ARCHIVO_CANVAS_FILTRADO]
DROP TABLE [dbo].[ARCHIVO_CARGA_CALIFICACIONES];
DROP TABLE [dbo].[ARCHIVOS_PROCESADOS];
DROP TABLE [dbo].[BITACORA];
DROP TABLE [dbo].[BITACORA_CARGA_CALIFICACIONES];
DROP TABLE [dbo].[BITACORA_GENERACION_REPORTE];
DROP TABLE [dbo].[BITACORA_MATERIAS_EXCEPCION];
DROP TABLE [dbo].[BITACORA_MATERIAS_NORMATIVA];
DROP TABLE [dbo].[BITACORA_NORMATIVA];
DROP TABLE [dbo].[BITACORA_PROCESO_AUTOMATICO];
DROP TABLE [dbo].[BITACORA_ROLES_ADMIN];
DROP TABLE [dbo].[BITACORA_SUBPERIODO_CAMPUS];
DROP TABLE [dbo].[BITACORA_SUBPERIODO_NACIONAL];
DROP TABLE [dbo].[CALIFICACIONES_ENVIADAS_BANNER];
DROP TABLE [dbo].[CALIFICACIONES_ENVIADAS_CONSOLIDADO];
DROP TABLE [dbo].[CALIFICACIONES_PERMITIDAS];
DROP TABLE [dbo].[CAT_BITACORAS];
DROP TABLE [dbo].[CATALOGO_NORMATIVAS];
DROP TABLE [dbo].[EXCEPCION_DE_MATERIAS];
DROP TABLE [dbo].[MATERIAS_EXCLUSIONES];
DROP TABLE [dbo].[MATERIAS_NORMATIVAS];
DROP TABLE [dbo].[ROLES_tmp];
DROP TABLE [dbo].[NORMATIVAS_tmp];
DROP TABLE [dbo].[ROLES-USUARIO];
DROP TABLE [dbo].[SUBPERIODOS_CAMPUS];
DROP TABLE [dbo].[SUBPERIODOS_NACIONAL];
DROP TABLE [dbo].[USUARIOS_tmp];
GO
GO
DROP PROCEDURE [dbo].[ReporteAvanceCapturado];
DROP PROCEDURE [dbo].[SP_ACTUALIZA_ESTATUS_CALIFICACIONES_ENVIADAS_BANNER];
DROP PROCEDURE [dbo].[SP_APLICAR_NORMATIVA];
DROP PROCEDURE [dbo].[SP_BITACORA];
DROP PROCEDURE [dbo].[SP_CRUD_ARCHIVOS_PROCESADOS];
DROP PROCEDURE [dbo].[sp_ejemplo];
DROP PROCEDURE [dbo].[SP_ENVIA_CORREOS];
DROP PROCEDURE [dbo].[SP_ESTAN_EN_MATERIAS_EXCEPCION];
DROP PROCEDURE [dbo].[SP_INSERT_VALORES_ARCHIVO_CANVAS];
DROP PROCEDURE [dbo].[SP_OBTENER_ATRIBUTO_PERIODO];
DROP PROCEDURE [dbo].[SP_OBTENER_INFO_NORMATIVA];
DROP PROCEDURE [dbo].[SP_PROBAR_BD];
DROP PROCEDURE [dbo].[SP_PROCESO_AUTOMATICO];
DROP PROCEDURE [dbo].[SP_PROCESO_SC];
DROP PROCEDURE [dbo].[SP_REVISAR_MATERIAS_NORMATIVAS];
DROP PROCEDURE [dbo].[SP_REVISAR_SEMANA_6Y12];
DROP PROCEDURE [dbo].[SP_TRAER_DATOS_GRUPOS];
DROP PROCEDURE [dbo].[SP_TRAER_PERIODO_ACTIVO];
DROP PROCEDURE [dbo].[SP_VALIDAR_GRUPOS_A_CANVAS];
DROP PROCEDURE [dbo].[SP_VALORES_ARCHIVO_CANVAS];
DROP PROCEDURE [dbo].[SP_VALORES_ARCHIVO_CANVAS_FILTRADO];
DROP PROCEDURE [dbo].[SP_CALIFICACIONES_EN_EXCEPCION];
GO
DROP PROCEDURE [dbo].[ListaCalificacionesAlumnosPorGrupo]
DROP PROCEDURE [dbo].[ReporteAvanceCapturado]
DROP PROCEDURE [dbo].[spConsulta_ConsultarMateriasPorAlumno]
DROP PROCEDURE [dbo].[spFiltro_ConsultarAlumnos]
