ALTER TABLE [dbo].[Bitacora_CargaCalificiones] drop CONSTRAINT [DF_Bitacora_CargaCalificiones_FechaRegistro]
ALTER TABLE [dbo].[Bitacora_Correos] drop CONSTRAINT [DF_Bitacora_Correos_FechaRegistro]
ALTER TABLE [dbo].[Bitacora_GeneracionReportes] drop CONSTRAINT [DF_Bitacora_GeneracionReportes_FechaRegistro]
ALTER TABLE [dbo].[Bitacora_MateriasExcepcion] drop CONSTRAINT [DF_Bitacora_MateriasExcepcion_FechaRegistro]
ALTER TABLE [dbo].[Bitacora_MateriasNormativa] drop CONSTRAINT [DF_Bitacora_MateriasNormativa_FechaRegistro]
ALTER TABLE [dbo].[Bitacora_Normativas] drop CONSTRAINT [DF_Bitacora_Normativas_FechaRegistro]
ALTER TABLE [dbo].[Bitacora_ProcesoAutomatico] drop CONSTRAINT [DF_Bitacora_ProcesoAutomatico]
ALTER TABLE [dbo].[Bitacora_ProcesoSC] drop CONSTRAINT [DF_Bitacora_ProcesoSC_FechaRegistro]
ALTER TABLE [dbo].[Bitacora_RolesAdmin] drop CONSTRAINT [DF_Bitacora_RolesAdmin_FechaRegistro]
ALTER TABLE [dbo].[Bitacora_SubPeriodoCampus] drop CONSTRAINT [DF_Bitacora_SubPeriodoCampus_FechaRegistro]
ALTER TABLE [dbo].[Bitacora_SubperiodoNacional] drop CONSTRAINT [DF_Bitacora_SubperiodoNacional_FechaRegistro]
ALTER TABLE [dbo].[CalificacionesEnviadasBanner] drop CONSTRAINT [DF_CalificacionesEnviadasBanner_FechaAgregado]
ALTER TABLE [dbo].[CatalogoBitacoras] drop CONSTRAINT [DF_CatalogoBitacoras_Nivel]
ALTER TABLE [dbo].[MateriasNormativas] drop CONSTRAINT [DF_MateriasNormativas_FechaAgregado]
ALTER TABLE [dbo].[Normativas] drop CONSTRAINT [DF_Normativas_FechaAgregado]
ALTER TABLE [dbo].[SubperiodosCampus] drop CONSTRAINT [DF_SubperiodosCampus_FechaAgregado]
ALTER TABLE [dbo].[SubperiodosNacionalCampusFechaFin] drop CONSTRAINT [DF_SuperiodosNacionalCampusFechaFin_FechaAgregado]
ALTER TABLE [dbo].[SubperiodosNacionalCampusFechaInicio] drop CONSTRAINT [DF_SuperiodosNacionalCampusFechaInicio_FechaAgregado]

ALTER TABLE [dbo].[Bitacora_CargaCalificiones] ADD  CONSTRAINT [DF_Bitacora_CargaCalificiones_FechaRegistro]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[Bitacora_Correos] ADD  CONSTRAINT [DF_Bitacora_Correos_FechaRegistro]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[Bitacora_GeneracionReportes] ADD  CONSTRAINT [DF_Bitacora_GeneracionReportes_FechaRegistro]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[Bitacora_MateriasExcepcion] ADD  CONSTRAINT [DF_Bitacora_MateriasExcepcion_FechaRegistro]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[Bitacora_MateriasNormativa] ADD  CONSTRAINT [DF_Bitacora_MateriasNormativa_FechaRegistro]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[Bitacora_Normativas] ADD  CONSTRAINT [DF_Bitacora_Normativas_FechaRegistro]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[Bitacora_ProcesoAutomatico] ADD  CONSTRAINT [DF_Bitacora_ProcesoAutomatico]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[Bitacora_ProcesoSC] ADD  CONSTRAINT [DF_Bitacora_ProcesoSC_FechaRegistro]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[Bitacora_RolesAdmin] ADD  CONSTRAINT [DF_Bitacora_RolesAdmin_FechaRegistro]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[Bitacora_SubPeriodoCampus] ADD  CONSTRAINT [DF_Bitacora_SubPeriodoCampus_FechaRegistro]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[Bitacora_SubperiodoNacional] ADD  CONSTRAINT [DF_Bitacora_SubperiodoNacional_FechaRegistro]  DEFAULT (getdate()) FOR [FechaRegistro]
ALTER TABLE [dbo].[CalificacionesEnviadasBanner] ADD  CONSTRAINT [DF_CalificacionesEnviadasBanner_FechaAgregado]  DEFAULT (getdate()) FOR [FechaAgregado]
ALTER TABLE [dbo].[CatalogoBitacoras] ADD  CONSTRAINT [DF_CatalogoBitacoras_Nivel]  DEFAULT (getdate()) FOR [FechaAgregado]
ALTER TABLE [dbo].[MateriasNormativas] ADD  CONSTRAINT [DF_MateriasNormativas_FechaAgregado]  DEFAULT (getdate()) FOR [FechaAgregado]
ALTER TABLE [dbo].[Normativas] ADD  CONSTRAINT [DF_Normativas_FechaAgregado]  DEFAULT (getdate()) FOR [FechaAgregado]
ALTER TABLE [dbo].[SubperiodosCampus] ADD  CONSTRAINT [DF_SubperiodosCampus_FechaAgregado]  DEFAULT (getdate()) FOR [FechaAgregado]
ALTER TABLE [dbo].[SubperiodosNacionalCampusFechaFin] ADD  CONSTRAINT [DF_SuperiodosNacionalCampusFechaFin_FechaAgregado]  DEFAULT (getdate()) FOR [FechaAgregado]
ALTER TABLE [dbo].[SubperiodosNacionalCampusFechaInicio] ADD  CONSTRAINT [DF_SuperiodosNacionalCampusFechaInicio_FechaAgregado]  DEFAULT (getdate()) FOR [FechaAgregado]